[project]
name = "cal2busy"
version = "0.1.0"
description = "Simple FastAPI script to merge calendars"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "icalendar>=6.3.1",
    "requests>=2.32.3",
    "uvicorn>=0.34.3",
]
